# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('permission', models.IntegerField(default=1)),
                ('app_id', models.CharField(default='abcd', max_length=128)),
                ('app_secret', models.CharField(default='123456789', max_length=128)),
                ('token', models.CharField(default='0', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
