# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuijieUser',
            fields=[
                ('stu_num', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('flow_used', models.CharField(default='0.0', max_length=10)),
                ('money', models.CharField(default='0.0', max_length=10)),
            ],
            options={
                'ordering': ('stu_num',),
            },
        ),
    ]
