# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-21 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruijie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruijieuser',
            name='stu_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
